global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    stack: cpe-sim-dev

scrape_configs:
  - job_name: cpe-sim
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9100
        labels:
          instance: cpe-sim-host
